---
# tasks file for leaf
#
- name: Configure NTP
  eos_config:
          src: ntp.j2
          provider: "{{ eos_api }}"

- name: Configure loopback 
  eos_config:
          src: loopback.j2
          provider: "{{ eos_api }}"

- name: Configure IP interfaces
  eos_config:
          src: ip_int.yml 
          provider: "{{ eos_api }}"

- name: Configure Leaf BGP
  eos_config:
          src: underlay_bgp.j2
          provider: "{{ eos_api }}"

- name: Create VLANs
  eos_config:
          src: vlans.j2
          provider: "{{ eos_api }}"

- name: Assign L2 Interfaces to VLAN
  eos_config:
          src: l2_int.j2
          provider: "{{ eos_api }}"

- name: Configure VXLAN
  eos_config:
          src: vxlan.j2
          provider: "{{ eos_api }}"

- name: Configure BGP Overlay
  eos_config:
          src: overlay_bgp.j2
          provider: "{{ eos_api }}"

- name: Configure BGP VLAN
  eos_config:
          src: evpn_l2.j2
          provider: "{{ eos_api }}"

- name: Configure EVPN L3
  eos_config:
          src: evpn_l3.j2
          provider: "{{ eos_api }}"
