---
# tasks file for leaf
#
- name: Configure NTP
  eos_config:
    src: ntp.j2
    provider: "{{ eos_api }}"

- name: Configure loopback 
  eos_config:
    src: loopback.j2
    provider: "{{ eos_api }}"

- name: Configure IP interfaces
  eos_config:
    src: ip_int.yml 
    provider: "{{ eos_api }}"

- name: Configure Leaf BGP
  eos_config:
    src: underlay_bgp.j2
    provider: "{{ eos_api }}"
