lo_interfaces:
        - name: Loopback0
          description: BGP RID
          address: 172.16.2.3


ip_interfaces:
        - name: eth1
          type: no switchport
          description: to-spine-1
          address: 10.13.56.5/31
          mtu: 9000
          status: no shutdown
        - name: eth2
          type: no switchport
          description: to-spine-2
          address: 10.13.57.5/31
          mtu: 9000
          status: no shutdown

bgp:
          local_as: 65003
          router_id: 172.16.2.3
          spines:
                  - 10.13.56.4
                  - 10.13.57.4

          spine_lo:
                  - 172.16.1.1
                  - 172.16.1.2

l2_interfaces:
        - name: eth3
          description: host3
          vlan: 40

